### ISSUE TITLE
Is this package Production Ready ?

### ISSUE THREAD

**Issue by beeeku** [MSG91/node-v2#1]
Hi There, 
Thanks for implementing v2 your API, it was long awaited feature. 
As there are no test cases and or coverage I was wondering if this is safe for production uses?
Thanks
Bikash

**Comment by beeeku** [comment]
Also just gone through the source code and found out these things 

1. Lots of try catches are there without error handling 
2. No Test Cases 
3. No Coding Standard is used ( Please use Eslint / JSHint & Prettier )
4. Previously I have implemented the case for special symbols by URL encoding the message string twice But when we are sending the message by POST there is no need of doing that.

Check out [https://github.com/lassjs/lass](https://github.com/lassjs/lass) If you want to see how a modern js package should look like. 
Hope you take this criticism in a constructive way. 
Can't wait to use this in production.
Bikash

**Comment by sarfarazansari** [comment]
@beeeku Thanks for looking into it. Would be great if you help us by making those changes and create a PR.
